version: 2
jobs:
  build:
    docker:
      - image: circleci/node:boron
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: NPM_CONFIG_PRODUCTION=false
      - run: npm install --prefix client
      - run: npm run build --prefix client

  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      HEROKU_APP: "whispering-savannah-73328"
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |  # this command is framework-dependent and may vary
            heroku git:remote -a $HEROKU_APP_NAME
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/master
            sleep 5  # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


              e59707b0-947d-4c92-aa45-2833e8c6e0de