version: 1

machine:
  services:
    - docker

dependencies:
  post:
    - NPM_CONFIG_PRODUCTION=false
    - npm install --prefix client
    - npm run build --prefix client

general:
  branches:
    only:
      - master

deployment:
  prod:
    branch: master
    heroku:
      appname: whispering-savannah-73328